spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hzwl
    username: root
    password: 0bc80571576c426b
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100  # 增加连接池最大连接数
      minimum-idle: 10  # 增加连接池最小空闲连接数
      connection-timeout: 30000  # 延长连接超时时间
      max-lifetime: 1800000  # 30分钟，保持原样
      connection-test-query: SELECT 1
      idle-timeout: 600000  # 10分钟，保持原样
      initialization-fail-timeout: -1  # 在连接失败时无限等待，直到连接成功或达到最大尝试次数
      pool-name: RentalPool1  # 设置连接池名称，可选

springfox:
  swagger2:
    enabled: true
    version: 2.9.2
  swagger-ui:
    enabled: true
    version: 2.9.2